import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Logo from '@public/icons/recruiter.svg';
import { ReactNode } from 'react';

type ILayout = {
  children: ReactNode;
};

const Layout: FC<ILayout> = ({ children }: ILayout) => {
  return (
    <div className="block w-100">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="shadow-lg fixed left-0 z-20 right-0 top-0 bg-white py-[28px] container w-100 items-center">
        <nav className="flex flex-row items-center justify-between">
          <Link passHref href="/">
            <Logo></Logo>
          </Link>
          <ul className="inline-flex flex-row items-center">
            <li className="mr-[34px]">
              <Link className="text-[16px] font-semibold" href="/">
                How it work
              </Link>
            </li>
            <li className="mr-[34px]">
              <Link className="text-[16px] font-semibold" href="/about">
                Testimony
              </Link>
            </li>
            <li className="mr-[34px]">
              <Link
                className="text-[16px] font-semibold"
                href="/blog/hello-world"
              >
                Services
              </Link>
            </li>
            <li className="mr-[34px]">
              <Link
                className="text-[16px] font-semibold"
                href="/blog/hello-world"
              >
                FAQ
              </Link>
            </li>
            <li className="mr-[34px]">
              <Link
                className="text-[16px] font-semibold"
                href="/blog/hello-world"
              >
                Contact Us
              </Link>
            </li>
            <li className="mr-[34px]">
              <Link
                className="text-[16px] font-semibold"
                href="/blog/hello-world"
              >
                Sign in
              </Link>
            </li>
            <li>
              <button className="text-white font-bold text-[14px] bg-primary rounded-[8px] w-[180px] h-[40px]">
                Register Now
              </button>
            </li>
          </ul>
        </nav>
      </header>
      <main className="block w-100 pt-[100px]">{children}</main>
      <footer className="bg-light-white">
        <div className="container pt-[56px] pb-[82px]">
          <div className="flex">
            <div className="inline-flex mr-[260px]">
              <p className="text-dark-grey text-[16px] text-normal w-[290px]">
                HumaHire is a marketplace that enables everyone to leverage the
                power of crowdsourcing to recruit.
              </p>
            </div>
            <div className="inline-flex">
              <ul>
                <li className="mb-[20px]">
                  <span className="text-[20px] font-bold text-black">
                    Product
                  </span>
                </li>
                <li className="mb-[16px]">
                  <a className="font-normal text-[16px] text-grey" href="/">
                    Employers
                  </a>
                </li>
                <li className="mb-[16px]">
                  <a className="font-normal text-[16px] text-grey" href="/">
                    Recruiter
                  </a>
                </li>
                <li className="mb-[16px]">
                  <a className="font-normal text-[16px] text-grey" href="/">
                    Jobseeker
                  </a>
                </li>
              </ul>
            </div>
            <div className="inline-flex ml-[40px]">
              <ul>
                <li className="mb-[20px]">
                  <span className="text-[20px] font-bold text-black">
                    Company
                  </span>
                </li>
                <li className="mb-[16px]">
                  <a className="font-normal text-[16px] text-grey" href="/">
                    About Us
                  </a>
                </li>
                <li className="mb-[16px]">
                  <a className="font-normal text-[16px] text-grey" href="/">
                    Privacy Policy
                  </a>
                </li>
                <li className="mb-[16px]">
                  <a className="font-normal text-[16px] text-grey" href="/">
                    Terms & Conditions
                  </a>
                </li>
                <li className="mb-[16px]">
                  <a className="font-normal text-[16px] text-grey" href="/">
                    Contact Us
                  </a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div className="container border-t border-light-grey py-[16px]">
          <div className="flex justify-between">
            <span className="font-normal text-grey text-[16px]">
              Copyright © 2022 HumaHire. All Rights Reserved.
            </span>
            <ul className="inline-flex flex-row">
              <li className="ml-4">
                <a href="/">Twit</a>
              </li>
              <li className="ml-4">
                <a href="/">Face</a>
              </li>
              <li className="ml-4">
                <a href="/">Link</a>
              </li>
            </ul>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Layout;
