name: HH-Landing-Page-Jobseeker Workflow

on:
  push:
    branches:
      - create-workflow

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ap-southeast-1
    
#      - name: Download Dev Env File
#        if: github.ref == 'refs/heads/create-workflow'
#        run: aws s3 cp s3://workflow-github-action/env-file/hh-be-core/develop/.env.staging .env.staging
    
      - name: Build Next.js
        run: npm install

      - name: Build
        run: npm run build

      - name: Archive build files
        uses: actions/upload-artifact@v2
        with:
          name: build-files
          path: .next

  Deploy:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Download build files
        uses: actions/download-artifact@v2
        with:
          name: build-files
      
      - name: Delete Stop and Delete Previous Next.js
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_DEV }}
          username: ${{ secrets.EC2_USERNAME_DEV }}
          key: ${{ secrets.EC2_PRIVATE_KEY_DEV }}
          script: |
            sudo rm -rf /home/ubuntu/landing-page/jobseeker/tmp
            sudo mkdir /home/ubuntu/landing-page/jobseeker/tmp 
      
      - name: Copy build files to EC2 instance
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST_DEV }}
          username: ${{ secrets.EC2_USERNAME_DEV }}
          key: ${{ secrets.EC2_PRIVATE_KEY_DEV }}
          source: .next
          target: /home/ubuntu/landing-page/jobseeker/tmp/.next

      - name: Install Dependencies and Run Next.js
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_DEV }}
          username: ${{ secrets.EC2_USERNAME_DEV }}
          key: ${{ secrets.EC2_PRIVATE_KEY_DEV }}
          script: |
            cd /home/ubuntu
            npm install
            npm run start
      