name: HH-Landing-Page-Jobseeker Workflow

on:
  push:
    branches:
      - create-workflow

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      #      - name: Configure AWS Credentials
      #        uses: aws-actions/configure-aws-credentials@v1
      #        with:
      #          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #          aws-region: ap-southeast-1

      #      - name: Download Dev Env File
      #        if: github.ref == 'refs/heads/create-workflow'
      #        run: aws s3 cp s3://workflow-github-action/env-file/hh-be-core/develop/.env.staging .env.staging

      - name: Build Next.js
        run: npm install

      - name: Build
        run: npm run build

      - name: Delete Stop and Delete Previous Next.js
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_DEV }}
          username: ${{ secrets.EC2_USERNAME_DEV }}
          key: ${{ secrets.EC2_PRIVATE_KEY_DEV }}
          script: |
            sudo rm -rf /home/ubuntu/landing-page/jobseeker/tmp
            sudo mkdir /home/ubuntu/landing-page/jobseeker/tmp

      - name: Copy SSH Key to File
        run: |
          echo "$EC2_PRIVATE_KEY_DEV" > EC2_KEY.pem
          chmod 600 EC2_KEY.pem
        env:
          EC2_PRIVATE_KEY_DEV: ${{ secrets.EC2_PRIVATE_KEY_DEV }}

      - name: Update known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST_DEV }} >> ~/.ssh/known_hosts

      - name: Copy build files to EC2 instance
        run: scp -i EC2_KEY.pem -r .next ${{ secrets.EC2_USERNAME_DEV }}@${{ secrets.EC2_HOST_DEV }}:/home/ubuntu/landing-page/jobseeker/tmp/.next

  Deploy:
    needs: Build
    runs-on: ubuntu-latest

    steps:
      - name: Install Dependencies and Run Next.js
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST_DEV }}
          username: ${{ secrets.EC2_USERNAME_DEV }}
          key: ${{ secrets.EC2_PRIVATE_KEY_DEV }}
          script: |
            cd /home/ubuntu
            npm install
            npm run start
